---
title: "Disney Mini  Project"
author: "Khulood Fahim, Zoya Azhar, and Zoya Alam"
date: "4/26/2019"
output: 
  html_document:
    code_folding: hide
---
Access our  data from github  [^1]
```{r message= FALSE, warning=FALSE}
library(tidyverse)
library(RMySQL)
library(ggthemes)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
```

### 1: Zoya Alam 

```{r}
disney_princesses <- db %>%
  dbGetQuery("SELECT t.id ID_TITLE, t.title, t.production_year, mi.id, mi.movie_id, mi.info_type_id, mi.info
FROM title t
JOIN movie_info  mi
ON t.id= mi.movie_id
WHERE title IN ('Snow White', 'The Little Mermaid', 'Aladdin', 'Beauty and the Beast',
 'Cinderella', 'Mulan', 'Sleeping Beauty', 'Pocahontas') AND info_type_id= 107 AND mi.id IN (2117948, 2120511, 2113802, 
 2063386, 2055452, 2159031, 2133626);")

gross_revenue <- c("34.1", "13.24", "109.86", "218.97",  "217.04", "141.58", "120.62")

disney_princesses_final <- cbind(disney_princesses, gross_revenue)


ggplot(disney_princesses_final, aes(x= production_year, y= as.numeric(as.character(gross_revenue)), color= title)) + geom_point(size=  10) + labs(x= "Production Year", y= "Gross Revenue (in millions of $)", color= "Movie", title = "The Disney Princess Market") +  theme_minimal()
```


### 3: Khulood

```{r}
emmawatson <- db %>% 
  dbGetQuery("SELECT ci.person_id, n.name, ci.movie_id, t.title, mi.info, t.production_year
FROM cast_info ci
JOIN name n
ON ci.person_id = n.id
JOIN title t
ON t.id = ci.movie_id
LEFT JOIN movie_info mi 
ON mi.movie_id = ci.movie_id
WHERE n.id = '4080909'
AND t.kind_id = 1
AND mi.info_type_id = 107
AND mi.info LIKE '%(USA)%';")
```

```{r message=FALSE, warning=FALSE}
emmawatson <- emmawatson %>% 
  collect()

emmawatson <- emmawatson %>% 
  separate(info, c('gross', 'date'), sep=" ")


emmawatson <- 
  emmawatson %>% 
  mutate(gross_2 = gsub("\\$", "", gross)) %>%
  mutate(gross_3 = gsub("\\,", "", gross_2))

emmawatson <- emmawatson %>%
  mutate(gross_4 = as.numeric(gross_3))

```

```{r  warning=FALSE}
emmawatson <- emmawatson %>%
  group_by(title, production_year) %>%
  summarise(maxgross = max(gross_4)) %>%
  arrange(desc(production_year)) 
```

```{r}
emmaplot <- emmawatson %>%
  ggplot(aes(x = title, y = maxgross)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90),
        axis.title.x = element_text()) +
  scale_y_continuous (labels = scales::comma) + 
  ggtitle("Max Gross Revenue of Emma Watson's Movies")+
  labs(x = "Movie Title", 
       y = "Highest Gross Revenue")
emmaplot
``` 

```{r message= FALSE,warning=FALSE}
lilyjames <- db %>%
  dbGetQuery("SELECT ci.person_id, n.name, ci.movie_id, t.title, mi.info, t.production_year
FROM cast_info ci
JOIN name n
ON ci.person_id = n.id
JOIN title t
ON t.id = ci.movie_id
LEFT JOIN movie_info mi 
ON mi.movie_id = ci.movie_id
WHERE n.id = '3291430'
AND t.kind_id = 1
AND mi.info_type_id = 107
AND mi.info LIKE '%(USA)%';")
```

```{r message=FALSE, warning=FALSE}
lilyjames <- lilyjames %>% 
  collect()

lilyjames <- lilyjames %>% 
  separate(info, c('gross', 'date'), sep=" ")


lilyjames <- 
  lilyjames %>% 
  mutate(gross_2 = gsub("\\$", "", gross)) %>%
  mutate(gross_3 = gsub("\\,", "", gross_2))

lilyjames <- lilyjames %>%
  mutate(gross_4 = as.numeric(gross_3))
```

```{r  message=FALSE,warning=FALSE}
lilyjames <- lilyjames %>%
  group_by(title, production_year) %>%
  summarise(maxgross = max(gross_4)) %>%
  arrange(desc(production_year)) 
```

```{r message=FALSE, warning=FALSE}
lilyplot <- lilyjames %>%
  ggplot(aes(x = title, y = maxgross)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous (labels = scales::comma) +
  ggtitle("Max Gross Revenue of Lily James's Movies") +
  labs(x = "Movie Title", 
       y = "Highest Gross Revenue")
lilyplot
``` 


[^1]: https://github.com/khfahim/Miniproject4Disney 